[#sec-named-type]
=== Named types

// Added
${syntax: prefixedTypeName specializedType namedType}

// Added
Named types are types that reference another type by name. User-defined types
can be introduced with their names. For example, the following declares a new
struct type `S`:

// Added
[source,p4]
----
struct S {
    bit<32> x;
    bit<32> y;
}
----

// Added
This type can then be referenced by its name, as can be seen in the parameter
type of the following example:

// Added
[source,p4]
----
void f(S s) {}
----

// Added
Here, `S` is a named type (`typeName`) that refers to the struct type defined earlier.

// 347 - Modified
Types such as struct, header, and header union types can be generic. In order
to use such a generic type it must be specialized with appropriate type
arguments. For example,

// 348
[source,p4]
----
// generic structure type
struct S<T> {
    T field;
    bool valid;
}

struct G<T> {
    S<T> s;
}

// specialize S by replacing 'T' with 'bit<32>'
const S<bit<32>> s = { field = 32w0, valid = false };
// Specialize G by replacing 'T' with 'bit<32>'
const G<bit<32>> g = { s = { field = 0, valid = false } };

// generic header type
header H<T> {
    T field;
}

// Specialize H by replacing 'T' with 'bit<8>'
const H<bit<8>> h = { field = 1 };
// Header stack produced from a specialization of a generic header type
H<bit<8>>[10] stack;

// Generic header union
header_union HU<T> {
    H<bit<32>> h32;
    H<bit<8>>  h8;
    H<T>       ht;
}

// Header union with a type obtained by specializing a generic header union type
HU<bit> hu;
----

// Added
To handle named types used as return types, the following production is also
used:

${syntax: identifier typeOrVoid}

[#sec-type-definition]
==== Type definitions (type constructors)

// Added
${syntax: typeDeclaration}

// Added
`typeDeclaration` introduces a user-defined type definition. These can be
referenced by name. Generic type definitions can be specialized with type
arguments to produce a type instance.

// Added
The internal representation of type definitions is as follows:

// Added
${syntax: nameTypeDefIR aliasTypeDefIR dataTypeDefIR objectTypeDefIR typeDefIR}

// Added
For example, `structTypeDeclaration` introduces a struct type definition,
`structTypeDefIR`:

// Added
${syntax: structTypeDefIR structTypeDeclaration}

// Added
Some type definitions like struct and header type definitions can be
polymorphic, meaning they can have type variables as parameters. On the other
hand, type definitions such as enum and type alias definitions can only be
monomorphic. Below table summarizes which kinds of type definitions can be
polymorphic:

// Added
ifndef::release[]
NOTE: Add a table for $is_monomorphic_typeDefIR here.
endif::[]

// Added
ifndef::release[]
NOTE: Add explainer on explicit and implicit type parameters for type definitions here.
endif::[]

==== Type resoultion

// Added
Notice that P4 has struct types, but the surface syntax does not have an
explicit construct for struct types. Instead, struct types are always
referenced by name. To easily handle named types in P4~IR~, the internal
representation of types contain representations for the referred types.

// Added
${syntax: structTypeIR}

// Added
For example, a struct type is represented as `structTypeIR` in P4~IR~. Thus,
after type checking, a named type in P4~16~ is resolved to its referred type in
P4~IR~. For named types referring to monomorphic type definitions, the resolved
type is simply the type defined by the type definition.

// Added
[source,p4]
----
enum E_t { A, B, C; }
void f(E_t e) {}
----

// Added
In the above example, the named type `E_t` is resolved to the enum type
`enumTypeIR`.

// Added
[source,p4]
----
struct S<T> { T t; }
void f(S<bit<32>> s) {}
----

// Added
In the above example, the named type `S<bit<32>>` is resolved to a
`structTypeIR`, where it specializes a `structTypeDefIR` with the type argument
`bit<32>`. Type specialization is discussed in detail in the next section.

[#sec-type-specialization]
==== Type specialization

// Added
${func-source: specialize_typeDefIR}
${func-prose: specialize_typeDefIR}

==== Type names

// Added
${syntax: prefixedTypeName identifier}

// Added
A `prefixedTypeName` and `identifier` may refer to either a monomorphic type
definition or a polymorphic type definition without type arguments. The names
can be prefixed by a dot (`.`) to refer to the top-level namespace.

// Added
On type checking, the referenced type definition is looked up by name. If the
referenced type definition is monomorphic, then the resolved type is simply the
type defined by the type definition. If the referenced type definition is
polymorphic (but without type arguments), then the resolved type is a
specialized type with no type arguments.

// Added
In some cases, the reference may be a type parameter. In other words, the type
is indeed a variable type, not a concrete type until it is bound to a type
argument. These are internally represented as:

${syntax: nameTypeDefIR}

===== Operations

// 627
Because functions and methods can be generic, they offer the possibility of
declaring values with types that are type variables:

// 628
[source,p4]
----
void f<T>() {
   T x; // the type of x is T, a type variable
}
----

// 629
The type of such objects is not known until the function is specialized with
specific type arguments.

// 630
Currently the only operations that are available for such values are assignment
(explicit through `=`, or implicit, through argument passing). This behavior is
similar to languages such as Java, and different from languages such as C++.

// 631
A future version of P4 may introduce a notion of _type constraints_ which would
enable more operations on such values. Because of this limitation, such values
are currently of limited utility.

===== Type checking

// Added
${rulegroup-source: Type_ok/prefixedTypeName-identifier}
${rulegroup-prose: Type_ok/prefixedTypeName-identifier}

==== Specialized types

// 340
A generic type may be specialized by specifying arguments for its type
variables. In cases where the compiler can infer type arguments, type
specialization is not necessary. When a type is specialized, all its type
variables must be bound.

// Added
ifndef::release[]
NOTE: P4-SpecTec currently does *not* infer type arguments for type
specialization, where it only performs inference for function and method calls.
endif::[]

// 341 - Modified
${syntax: specializedType}

// 342
For example, the following extern declaration describes a generic block of
registers, where the type of the elements stored in each register is an
arbitrary `T`.

// 343
[source,p4]
----
extern Register<T> {
    Register(bit<32> size);
    T read(bit<32> index);
    void write(bit<32> index, T value);
}
----

// 344
The type `T` has to be specified when instantiating a set of registers, by
specializing the Register type:

// 345
[source,p4]
----
Register<bit<32>>(128) registerBank;
----

// 346
The instantiation of `registerBank` is made using the `Register` type
specialized with the `bit<32>` bound to the `T` type argument.

===== Type checking

// Added
${rulegroup-source: Type_ok/specializedType}
${rulegroup-prose: Type_ok/specializedType}
