=== Synthesized types and values

// 317 - Modified
For the purposes of type-checking the P4 compiler can synthesize some type
representations which cannot be directly expressed by users.

// Added
These types and values are represented as:

// Added
${syntax: synthesizedTypeIR synthesizedValue}

[#sec-default]
==== Default

// 652 - Modified
A left-value can be initialized automatically with a default value of the
suitable type using:

// Added
${syntax: defaultExpression}

// Added
Internally, the type and value of `+...+` itself are represented as:

// Added
${syntax: defaultTypeIR defaultValue}

===== Operations

// Added
For example:

// 653
[source,p4]
----
struct S {
     bit<32> b32;
     bool b;
}

enum int<8> N0 {
   one = 1,
   zero = 0,
   two = 2
}

enum N1 {
     A, B, C, F
}

S s0 = ...;  // initialize s0 with the default value { 0, false }
N0 n0 = ...;  // initialize n0 with the default value 0
N1 n1 = ...;  // initialize n1 with the default value N1.A
----

// Added
See <<sec-default-expression>> for semantics of default initialization.

// Added
ifndef::release[]
NOTE: The default type and value is new. Because every expressions must have
a type and value, we need to represent those of `+...+`.
endif::[]

===== Well-formedness

// Added
${rulegroup-source: Type_wf/defaultTypeIR}
${rulegroup-prose: Type_wf/defaultTypeIR}

[#sec-invalid-header]
==== Invalid headers

// 554
The expression `+{#}+` represents an invalid header of some type, but it can be
any header or header union type. A P4 compiler may require an explicit cast on
this expression in cases where it cannot determine the particular header or
header union type from the context.

// 555 - Modified
${syntax: invalidHeaderExpression}

// 558
Note that the `+#+` character cannot be misinterpreted as a preprocessor
directive, since it cannot be the first character on a line when it occurs in
the single lexical token `+{#}+`, which may not have whitespace or any other
characters between those shown.

// Added
Internally, the type and value of `+{#}+` itself are represented as:

// Added
${syntax: invalidHeaderTypeIR invalidHeaderValue}

===== Operations

// 556
For example:

// 557
[source,p4]
----
header H { bit<32> x; bit<32> y; }
H h;
h = {#};   // This makes the header h become invalid
----

// Added
ifndef::release[]
NOTE: The invalid header type and value is new. Because every expressions
must have a type and value, we need to represent those of `+{#}+`.
endif::[]

===== Well-formedness

// Added
${rulegroup-source: Type_wf/invalidHeaderTypeIR}
${rulegroup-prose: Type_wf/invalidHeaderTypeIR}

[#sec-sequence]
==== Sequences

// 494 - Modified
A sequence expression is written using curly braces, with each element
separated by a comma:

// 495 - Modified
${syntax: sequenceElementExpression
          sequenceOrRecordElementExpression
          sequenceOrRecordExpression}

// Added
The type of a sequence expression is a sequence type. Its value is a sequence
value.

// Added
${syntax: sequenceTypeIR sequenceValue}

===== Operations

// 496 - Modified
Sequence expressions can be assigned to expressions of type `tuple`, `struct`
or `header`, and can also be passed as arguments to methods. Sequences may be
nested.

// 489 - Modified
For instance, sequences can be assigned to other tuples with the same type:

// 490
[source,p4]
----
tuple<bit<32>, bool> x = { 10, false };
----

// 497 - Modified
The following program fragment uses a sequence expression to pass several
header fields simultaneously to a learning provider:

// 498
[source,p4]
----
extern LearningProvider<T> {
    LearningProvider();
    void learn(in T data);
}

LearningProvider<tuple<bit<48>, bit<32>>>() lp;

lp.learn( { hdr.ethernet.srcAddr, hdr.ipv4.src } );
----

// 499 - Modified
A sequence may be used to initialize a structure if the tuple has the same
number of elements as fields in the structure. The effect of such an
initializer is to assign the n^th^ element of the tuple to the n^th^ field in
the structure:

// 500
[source,p4]
----
struct S {
    bit<32> a;
    bit<32> b;
}
const S x = { 10, 20 }; // a = 10, b = 20
----

// 501 - Modified
Sequence expressions that have `+...+` as their last element are allowed to
give values to only a subset of the fields of the struct or header type to
which it evaluates. Any field names not given a value explicitly will be given
their default value (see <<sec-initializing-with-default-values>>).

// Added
ifndef::release[]
NOTE: The sequence type is newly introduced. In the current P4 language
specification, sequence expressions are referred to as tuple expressions, and
(somewhat confusingly and implicitly) has tuple type. However, this is
problematic since tuples have limited casting rules that cannot be applied to
several initialization scenarios. Thus, we introduce sequence types to
represent the expression sequence within curly braces, apart from tuple types.
endif::[]

===== Well-formedness

// Added
${rulegroup-source: Type_wf/sequenceTypeIR}
${rulegroup-prose: Type_wf/sequenceTypeIR}

[#sec-record]
==== Records

// 506 - Modified
One can write record expressions that evaluate to a structure or header. The
syntax of these expressions is given by:

// 507 - Modified
${syntax: recordElementExpression
          sequenceOrRecordElementExpression
          sequenceOrRecordExpression}

// Added
Internally, the type and value of a record expression are represented as:

// Added
${syntax: recordTypeIR recordValue}

===== Operations

// 509
The following example shows a structure-valued expression used in an equality
comparison expression:

// 510
[source,p4]
----
struct S {
    bit<32> a;
    bit<32> b;
}

void f() {
  S s;

  // Compare s with a record expression
  bool b = s == (S) { a = 1, b = 2 };
}
----

// 511
Record expressions can be used in the right-hand side of assignments, in
comparisons, in field selection expressions, and as arguments to functions,
method or actions. Record expressions are not left values.

// 512
Record expressions that do not have `+...+` as their last element must provide
a value for every member of the struct or header type to which it evaluates, by
mentioning each field name exactly once.

// 513
Record expressions that have `+...+` as their last element are allowed to give
values to only a subset of the fields of the struct or header type to which it
evaluates. Any field names not given a value explicitly will be given their
default values (see <<sec-initializing-with-default-values>>).

// 514
The order of the fields of the `struct` or `header` type does not need to match
the order of the values of the structure-valued expression.

// 515
It is a compile-time error if a field name appears more than once in the same
structure-valued expression.

// Added
ifndef::release[]
NOTE: The record type and value is new. Because every expression must have
a type and value, we need to represent those of `{ recordElementExpression
optTrailingComma }`.
endif::[]

===== Well-formedness

// Added
${rulegroup-source: Type_wf/recordTypeIR}
${rulegroup-prose: Type_wf/recordTypeIR}

==== Sets

// Added
${syntax: setTypeIR}

// 318 - Modified
The set type describes _sets_ of values of some type `T`. Set types can only
appear in restricted contexts in P4 programs. For example, the range expression
`8w5 .. 8w8` describes a set containing the 8-bit numbers 5, 6, 7, and 8, so
its type is `set<bit<8>>;`. This expression can be used as a label in a
`select` expression (see <<sec-select>>), matching any value in this range. Set
types cannot be named or declared by P4 programmers, they are only synthesized
by the compiler internally and used for type-checking.

// Added
Set values are represented as:

// Added
${syntax: setValue}

===== Operations

// 519 - Modified
Some P4 expressions denote sets of values. These expressions can appear only in
a few contexts--parsers and table entries. For example, the `select` expression
(<<sec-select>>) has the following structure:

// 520
[source,p4]
----
select (expression) {
   set1: state1;
   set2: state2;
   // More labels omitted
}
----

// 521
Here the expressions `set1, set2`, etc. evaluate to sets of values and the
`select` expression tests whether `expression` belongs to the sets used as
labels.

// 522 - Modified
${syntax: keysetExpression tupleKeysetExpression
          simpleKeysetExpressionList simpleKeysetExpression}

// 523
The mask (`&&&`) and range (`..`) operators have the same precedence; the just
above the `?:` operator.

[#sec-singleton-set]
====== Singleton sets

// 524
In a set context, expressions denote singleton sets. For example, in the
following program fragment,

// 525
[source,p4]
----
select (hdr.ipv4.version) {
   4: continue;
}
----

// 526
The label `4` denotes the singleton set containing the `int` value `4`.

[#sec-universal-set]
====== The universal set

// 527
In a set context, the expressions `default` or `_` denote the universal set,
which contains all possible values of a given type:

// 528
[source,p4]
----
select (hdr.ipv4.version) {
   4: continue;
   _: reject;
}
----

[#sec-mask-set]
====== Masks

// 529
The infix operator `&&&` takes two arguments of the same numeric type
(<<sec-numeric-values>>), and creates a value of the same type. The right value
is used as a "mask", where each bit set to `0` in the mask indicates a "don't
care" bit. More formally, the set denoted by `a &&& b` is defined as follows:

// 530
[source,p4]
----
a &&& b = { c where a & b = c & b }
----

// 531
For example:

// 532
[source,p4]
----
8w0x0A &&& 8w0x0F
----

// 533
denotes a set that contains 16 different `bit<8>` values, whose bit-pattern is
`XXXX1010`, where the value of an `X` can be any bit. Note that there may be
multiple ways to express a keyset using a mask operator--e.g., `8w0xFA &&&
8w0x0F` denotes the same keyset as in the example above.

// 534
Similar to other binary operations, the mask operator allows the compiler to
automatically insert casts to unify the argument types in certain situations
(<<sec-implicit-cast>>).

// 535
P4 architectures may impose additional restrictions on the expressions on the
left and right-hand side of a mask operator: for example, they may require that
either or both sub-expressions be compile-time known values.

[#sec-range-set]
====== Ranges

// 536
The infix operator `..` takes two arguments of the same numeric type `T`
(<<sec-numeric-values>>), and creates a value of the type `set<T>`. The set
contains all values numerically between the first and the second, inclusively.
For example:

// 537
[source,p4]
----
4s5 .. 4s8
----

// 538
denotes a set of 4 consecutive `int<4>` values `4s5, 4s6, 4s7`, and `4s8`.

// 539
Similar to other binary operations, the range operator allows the compiler to
automatically insert casts to unify the argument types in certain situations
(<<sec-implicit-casts>>).

// 540
A range where the second value is smaller than the first one represents an
empty set.

====== Products

// 541
Multiple sets can be combined using Cartesian product:

// 542
[source,p4]
----
select(hdr.ipv4.ihl, hdr.ipv4.protocol) {
     (4w0x5, 8w0x1): parse_icmp;
     (4w0x5, 8w0x6): parse_tcp;
     (4w0x5, 8w0x11): parse_udp;
     (_, _): accept; }
----

// 543
The type of a product of sets is a set of sequences or tuples.

===== Well-formedness

// Added
${rulegroup-source: Type_wf/setTypeIR}
${rulegroup-prose: Type_wf/setTypeIR}

[#sec-table-metadata]
==== Table metadata

// 982
A `table` can be invoked by calling its `apply` method. Calling an apply method
on a table instance returns a value with a table metadata `struct` type with
three fields. This structure is synthesized by the compiler automatically. For
each `table T`, the compiler synthesizes a table metadata `enum` and a
`struct`, shown in pseudo-P4:

// 983
[source,p4pseudo]
----
enum action_list(T) {
   // one field for each action in the actions list of table T
}
struct apply_result(T) {
    bool hit;
    bool miss;
    action_list(T) action_run;
}
----

===== Operations

// 984
The evaluation of the `apply` method sets the `hit` field to `true` and the
field `miss` to `false` if a match is found in the lookup-table; if a match is
not found `hit` is set to `false` and `miss` to `true`. These bits can be used
to drive the execution of the control-flow in the control block that invoked
the table:

// 985
[source,p4]
----
if (ipv4_match.apply().hit) {
    // there was a hit
} else {
    // there was a miss
}

if (ipv4_host.apply().miss) {
    ipv4_lpm.apply(); // Look up the route only if host table missed
}
----

// 986
The `action_run` field indicates which kind of action was executed
(irrespective of whether it was a hit or a miss). It can be used in a switch
statement:

// 987
[source,p4]
----
switch (dmac.apply().action_run) {
    Drop_action: { return; }
}
----

// Added
Internally, the type and value of table metadata are represented as:

// Added
${syntax: tableMetadataTypeIR tableMetadataValue}

===== Well-formedness

// Added
${rulegroup-source: Type_wf/tableMetadataTypeIR}
${rulegroup-prose: Type_wf/tableMetadataTypeIR}
