[#sec-variable-declaration]
=== Variable declarations

// 674
Local variables are declared with a type, a name, and an optional initializer
(as well as an optional annotation):

// 675 - Modified
${syntax: variableDeclaration initializerOpt initializer}

// 676
Variable declarations without an initializer are uninitialized (except for
headers and other header-related types, which are initialized to invalid in the
same way as described for direction `out` parameters in
<<sec-call-convention>>). The language places few restrictions on the types of
variables: most P4 types that can be written explicitly can be used (e.g.,
base types, `struct`, `header`, header stack, `tuple`). However, it is
impossible to declare variables with type `int`, or with types that are only
synthesized by the compiler (e.g., `set`) In addition, variables of type
`parser`, `control`, `package`, or `extern` types must be declared using
instantiations (see <<sec-instantiation-declaration>>).

// 677
Reading the value of a variable that has not been initialized yields an
undefined result. The compiler should attempt to detect and emit a warning in
such situations.

// Added
ifndef::release[]
NOTE: P4-SpecTec implements zero-initialization for local variables.
endif::[]

// 678
Variable declarations can appear in the following locations within a P4
program:

// 679 - Modified
* In a block statement,
* In a `parser` state,
// * In an `action` body,
* In a `control` block's `apply` sub-block,
* In the list of local declarations in a `parser`, and
* In the list of local declarations in a `control`.

// Added
Note that variable declarations _cannot_ appear at the top level of a P4
program.

// 680
Variables have local scope, and behave like stack-allocated variables in
languages such as C. The value of a variable is never preserved from one
invocation of its enclosing block to the next. In particular, variables cannot
be used to maintain state between different network packets.

==== Type checking

// Added
Variable declarations are type checked using the following relation:

// Added
${relation-title-source: VarDecl_ok}
${relation-title-prose: VarDecl_ok}

// Added
After typing, variable declarations are represented in P4~IR~ as:

// Added
${syntax: variableDeclarationIR initializerIR}

// Added
These are produced by the following rules:

// Added
${rulegroup-source: VarDecl_ok}
${rulegroup-prose: VarDecl_ok}

==== Runtime evaluation

// Added
Variable declarations are evaluated at runtime using the following relation:

// Added
${relation-title-source: VarDecl_eval}
${relation-title-prose: VarDecl_eval}

// Added
The result of evaluating a variable declaration is:

// Added
${syntax: continueEmptyResult
          exitResult
          abortResult
          declarationResult}

// Added
See <<sec-exit-statement>> for how `exitResult` may occur. The relation is
defined by the following rule:

// Added
${rulegroup-source: VarDecl_eval}
${rulegroup-prose: VarDecl_eval}

// Added
ifndef::release[]
NOTE: Currently in P4-SpecTec, instantiation of a variable declaration is
implemented as a no-op. But, instantiation _may_ occur within the right-hand
side, initializer expression. Ideally, revisit this.
endif::[]
