[#sec-constant-declaration]
=== Constant declarations

// 669
Constant values are defined with the syntax:

// 670 - Modified
${syntax: constantDeclaration initializer}

// 673
// 671 - Modified
The `initializer` expression must be a local compile-time known value. A
constant declaration introduces a constant whose value has the specified type.
The following are all legal constant declarations:

// 672
[source,p4]
----
const bit<32> COUNTER = 32w0x0;
struct Version {
    bit<32> major;
    bit<32> minor;
}
const Version version = { 32w0, 32w0 };
----

==== Type checking

// Added
Constant declarations are type checked with the relation:

${relation-title-source: ConstDecl_ok}
${relation-title-prose: ConstDecl_ok}

// Added
After typing, in P4~IR~, constant declarations have the syntax:

// Added
${syntax: constantDeclarationIR constantInitializerIR}

// Added
Notice that `constantInitializerIR` is reduced to a `value` in P4~IR~, where
`value` is computed from `initializer` via local compile-time evaluation. It is
defined by the following rule:

// Added
${rulegroup-source: ConstDecl_ok}
${rulegroup-prose: ConstDecl_ok}

// Added
When used as a top-level declaration, constant declarations are typed with:

// Added
${rulegroup-source: Decl_ok/constantDeclaration}
${rulegroup-prose: Decl_ok/constantDeclaration}

// Added
==== Compile-time evaluation

// Added
Constant declarations are evaluated during instantiation phase with:

// Added
${relation-title-source: ConstDecl_inst}
${relation-title-prose: ConstDecl_inst}

// Added
It is defined by the following rule:

// Added
${rulegroup-source: ConstDecl_inst}
${rulegroup-prose: ConstDecl_inst}

// Added
When used as a top-level declaration, constant declarations are compile-time
evaluated with:

// Added
${rulegroup-source: Decl_inst/constantDeclarationIR}
${rulegroup-prose: Decl_inst/constantDeclarationIR}

// Added
==== Runtime evaluation

// Added
Constant declarations are evaluated at runtime using the following relation:

// Added
${relation-title-source: ConstDecl_eval}
${relation-title-prose: ConstDecl_eval}

// Added
${rulegroup-source: ConstDecl_eval}
${rulegroup-prose: ConstDecl_eval}
