[#sec-function-declaration]
=== Function declarations

// Added
Function declarations introduce user-defined functions into a P4 program.
<<sec-user-defined-function>> describes the semantics of user-defined functions
in P4.

// Added
${syntax: functionPrototype functionDeclaration}

==== Type checking

// Added
Function declarations are type checked with the relation:

// Added
${relation-title-source: FuncDecl_ok}
${relation-title-prose: FuncDecl_ok}

// Added
After type checking, function declarations are represented in P4~IR~ as:

// Added
${syntax: functionPrototypeIR functionDeclarationIR}

// Added
They are produced by the following rule:

// Added
${rulegroup-source: FuncDecl_ok}
${rulegroup-prose: FuncDecl_ok}

// Added
When used as a top-level declaration, function declarations are typed with:

// Added
${rulegroup-source: Decl_ok/functionDeclaration}
${rulegroup-prose: Decl_ok/functionDeclaration}

// Added
==== Compile-time evaluation

// Added
At compile-time, function declarations are loaded into the context with the relation:

// Added
${relation-title-source: FuncDecl_inst}
${relation-title-prose: FuncDecl_inst}

// Added
It is defined by the following rule:

// Added
${rulegroup-source: FuncDecl_inst}
${rulegroup-prose: FuncDecl_inst}

// Added
When used as a top-level declaration, function declarations are loaded with:

// Added
${rulegroup-source: Decl_inst/functionDeclarationIR}
${rulegroup-prose: Decl_inst/functionDeclarationIR}
