[#sec-action-declaration]
=== Action declarations

// Added
``action`` declarations introduce actions:

// Added
${syntax: actionDeclaration}

// Added
<<sec-action>> describes the semantics of actions.

==== Type checking

// Added
Action declarations are type checked with the relation:

// Added
${relation-title-source: ActionDecl_ok}
${relation-title-prose: ActionDecl_ok}

// Added
After type checking, action declarations are represented in P4~IR~ as:

// Added
${syntax: actionDeclarationIR}

// Added
These are produced by the following rule:

// Added
${rulegroup-source: ActionDecl_ok}
${rulegroup-prose: ActionDecl_ok}

// Added
When used as a top-level declaration, action declarations are typed with:

// Added
${rulegroup-source: Decl_ok/actionDeclaration}
${rulegroup-prose: Decl_ok/actionDeclaration}

// Added
==== Compile-time evaluation

// Added
At compile-time, action declarations are loaded into the context with the relation:

// Added
${relation-title-source: ActionDecl_inst}
${relation-title-prose: ActionDecl_inst}

// Added
It is defined by the following rule:

// Added
${rulegroup-source: ActionDecl_inst}
${rulegroup-prose: ActionDecl_inst}

// Added
When used as a top-level declaration, action declarations are loaded with:

${rulegroup-source: Decl_inst/actionDeclarationIR}
${rulegroup-prose: Decl_inst/actionDeclarationIR}
