[#sec-extern-object-declaration]
=== Extern object declarations

// Added
An extern object declaration introduces an extern object.

// Added
${syntax: externObjectDeclaration
          externConstructorOrMethodPrototype
          externConstructorOrMethodPrototypeList}

// Added
See <<sec-extern-object>> for how extern objects are internally represented. An
extern object declaration includes its constructors and methods, to be
explained in the following sections.

[#sec-extern-method-declaration]
==== Extern methods

// Added
Extern objects can have methods, which are declared using the following syntax:

// Added
${syntax: externMethodPrototype}

// Added
See <<sec-extern-method>> for details on how extern methods are represented
internally.

===== Type checking

// Added
Extern methods are type checked using the following relation:

// Added
${relation-title-source: ExternMethod_ok}
${relation-title-prose: ExternMethod_ok}

// Added
After type checking, in P4~IR~, an extern method declaration is represented as:

// Added
${syntax: externMethodPrototypeIR}

// Added
These are produced by:

// Added
${rulegroup-source: ExternMethod_ok}
${rulegroup-prose: ExternMethod_ok}

[#sec-extern-constructor-declaration]
==== Extern constructors

// Added
Extern objects may have constructors, which are declared using the following syntax:

// Added
${syntax: externConstructorPrototype}

===== Type checking

// Added
Extern constructors are type checked using the following relation:

// Added
${relation-title-source: ExternConstructor_ok}
${relation-title-prose: ExternConstructor_ok}

// Added
After type checking, in P4~IR~, an extern constructor declaration is represented as:

// Added
${syntax: externConstructorPrototypeIR}

// Added
These are produced by:

// Added
${rulegroup-source: ExternConstructor_ok}
${rulegroup-prose: ExternConstructor_ok}

==== Type checking

// Added
After type checking, an extern object declaration is represented in P4~IR~
as:

${syntax: externObjectDeclarationIR
          externConstructorPrototypeIR
          externMethodPrototypeIR}

// Added
${rulegroup-source: Decl_ok/externObjectDeclaration}
${rulegroup-prose: Decl_ok/externObjectDeclaration}

==== Compile-time evaluation

// Added
At comile-time, extern object declarations are loaded into the context by:

// Added
${rulegroup-source: Decl_inst/externObjectDeclarationIR}
${rulegroup-prose: Decl_inst/externObjectDeclarationIR}
