[#sec-enum-type-declaration]
=== Enum type declaration

// Added
An enumeration type is defined using the following syntax:

// Added
${syntax: enumTypeDeclaration namedExpressionList namedExpression}

// Added
After type checking, enum type declarations are represented as follows:

${syntax: enumTypeDeclarationIR namedValueListIR namedValueIR}

// Added
See <<sec-enum>> for more details on enums.

[#sec-enum-type-declaration-serializable]
==== Enum type declarations without an underyling type

===== Type checking

// Added
${rulegroup-source: Decl_ok/enumTypeDeclaration-non-serializable}
${rulegroup-prose: Decl_ok/enumTypeDeclaration-non-serializable}

===== Compile-time evaluation

// Added
At compile-time, enum type declarations are loaded into the context by:

// Added
${rulegroup-source: Decl_inst/enumTypeDeclarationIR-non-serializable}
${rulegroup-prose: Decl_inst/enumTypeDeclarationIR-non-serializable}

[#sec-enum-type-declaration-non-serializable]
==== Enum type declarations with an underlying type

===== Type checking

// Added
${rulegroup-source: Decl_ok/enumTypeDeclaration-serializable}
${rulegroup-prose: Decl_ok/enumTypeDeclaration-serializable}

// Added
An enum field is type-checked as follows:

// Added
${relation-title-source: Enum_serializable_field_ok}
${relation-title-prose: Enum_serializable_field_ok}

// Added
${rulegroup-source: Enum_serializable_field_ok}
${rulegroup-prose: Enum_serializable_field_ok}

// Added
A list of enum fields is type-checked with the following relation:

// Added
${relation-title-source: Enum_serializable_fieldList_ok}
${relation-title-prose: Enum_serializable_fieldList_ok}

===== Compile-time evaluation

// Added
At compile-time, enum type declarations are loaded into the context by:

// Added
${rulegroup-source: Decl_inst/enumTypeDeclarationIR-serializable}
${rulegroup-prose: Decl_inst/enumTypeDeclarationIR-serializable}
