=== Typedef declaration

// Added
A `typedef` or `type` declaration introduces an alias for an existing type.

// Added
${syntax: typedef typedefDeclaration}

// Added
In P4~IR~, `typedef` and `type` declarations are represented as:

// Added
${syntax: typedefIR typedefDeclarationIR}

[#sec-typedef-declaration]
==== `typedef` declaration

// Added
See <<sec-typedef>> for more details about `typedef` aliases.

===== Type checking

// Added
${rulegroup-source: Decl_ok/typedefDeclaration-typedef}
${rulegroup-prose: Decl_ok/typedefDeclaration-typedef}

===== Compile-time evaluation

// Added
At compile-time, ``typedef``s are loaded into the context with:

// Added
${rulegroup-source: Decl_inst/typedefDeclarationIR-typedef}
${rulegroup-prose: Decl_inst/typedefDeclarationIR-typedef}

[#sec-newtype-declaration]
==== New type declaration

// Added
See <<sec-newtype>> for more details about new type aliases.

===== Type checking

// Added
${rulegroup-source: Decl_ok/typedefDeclaration-newtype}
${rulegroup-prose: Decl_ok/typedefDeclaration-newtype}

===== Compile-time evaluation

// Added
At compile-time, ``type``s are loaded into the context with:

// Added
${rulegroup-source: Decl_inst/typedefDeclarationIR-newtype}
${rulegroup-prose: Decl_inst/typedefDeclarationIR-newtype}
