=== Predefined annotations

// 1193
Annotation names that start with lowercase letters are reserved for the
standard library and architecture. This document pre-defines a set of
"standard" annotations in <<sec-p4-reserved-annotations>>. We expect that this
list will grow. We encourage custom architectures to define annotations
starting with a manufacturer prefix: e.g., an organization named X would use
annotations named like `@X_annotation`

[#sec-optional-parameter-annotations]
==== Optional parameter annotations

// 1194
A parameter to a package, parser type, control type, extern method, extern
function or extern object constructor can be annotated with `@optional` to
indicate that the user does not need to provide a corresponding argument for
that parameter. The meaning of a parameter with no supplied value is
target-dependent.

[#sec-table-action-annotations]
==== Annotations on the table action list

// 1195
The following two annotations can be used to give additional information to the
compiler and control-plane about actions in a table. These annotations have no
bodies.

// 1196
* `@tableonly`: actions with this annotation can only appear within the table,
  and never as default action.
* `@defaultonly`: actions with this annotation can only appear in the default
  action, and never in the table.

// 1197
[source,p4]
----
table t {
    actions = {
       a,              // can appear anywhere
       @tableonly b,   // can only appear in the table
       @defaultonly c, // can only appear in the default action
    }
    /* body omitted */
}
----

// Added
ifndef::release[]
NOTE: `@tableonly` and `@defaultonly` are currently unimplemented in P4-SpecTec.
endif::[]

[#sec-control-plane-api-annotations]
==== Control-plane API annotations

// 1198
The `@name` annotation directs the compiler to use a different local name when
generating the external APIs used to manipulate a language element from the
control plane. This annotation takes a local compile-time known value of type
`string` (typically a string literal). In the following example, the
fully-qualified name of the table is `c_inst.t1`.

// 1199
[source,p4]
----
control c( /* parameters omitted */ )() {
    @name("t1") table t { /* body omitted */ }
    apply { /* body omitted */ }
}
c() c_inst;
----

// 1200
The `@hidden` annotation hides a controllable entity, e.g. a table, key,
action, or extern, from the control plane. This effectively removes its
fully-qualified name (<<sec-fully-qualified-names>>). This annotation does
not have a body.

// Added
ifndef::release[]
NOTE: `@hidden` is currently unimplemented in P4-SpecTec.
endif::[]

===== Restrictions

// 1201
Each element may be annotated with at most one `@name` or `@hidden` annotation,
and each control plane name must refer to at most one controllable entity. This
is of special concern when using an absolute `@name` annotation: if a type
containing a `@name` annotation with an absolute pathname (i.e., one starting
with a dot) is instantiated more than once, it will result in the same name
referring to two controllable entities.

// 1202
[source,p4]
----
control noargs();
package top(noargs c1, noargs c2);

control c() {
    @name(".foo.bar") table t { /* body omitted */ }
    apply { /* body omitted */ }
}
top(c(), c()) main;
----

// 1203
Without the `@name` annotation, this program would produce two controllable
entities with fully-qualified names `main.c1.t` and `main.c2.t`. However, the
`@name(".foo.bar")` annotation renames table `t` in both instances to
`foo.bar`, resulting in one name that refers to two controllable entities,
which is illegal.

==== Concurrency control annotations

// 1204
The `@atomic` annotation, described in <<sec-concurrency-model>> can be used to
enforce the atomic execution of a code block.

// Added
ifndef::release[]
NOTE: `@atomic` is currently unimplemented in P4-SpecTec.
endif::[]

[#sec-branch-annotations]
==== Branch prediction annotations

// 1205
The `@likely` and `@unlikely` annotation can be used on blocks that are used in
`if`-`else` or `switch` statements to hint when a branch is likely or unlikely
to be taken.

// 1206
[source.p4]
----
if (error_failure) @unlikely {
    /* code that is unlikely to execute as the condition is probably false */
}

switch(value) {
    1: @likely {
        /* code for the most common case */
       }
    2: { /* ... */ }
    default: @unlikely {
        /* code for rare case */
    }
}
----

// 1207
These annotations have no effect on the semantics of the program; they are just
hints to help an optimizer. A warning may be issued if a `@likely` block is
found to never execute or an `@unlikely` block will always execute, but is not
required.

// Added
ifndef::release[]
NOTE: `@likely` and `@unlikely` are currently unimplemented in P4-SpecTec.
endif::[]

[#sec-value-set-annotations]
==== Value set annotations

// 1208
The `@match` annotation, described in <<sec-select-expression>>, is used to
specify a `match_kind` value other than the default `match_kind` of `exact` for
a field of a `value_set`.

// Added
ifndef::release[]
NOTE: `@match` is currently unimplemented in P4-SpecTec.
endif::[]

[#sec-extern-annotations]
==== Extern function/method annotations

// 1209
Various annotations may appear on extern function and method declarations to
describe limitations on the behavior and interactions of those functions. By
default extern functions might have any effect on the environment of the P4
program and might interact in non-trivial ways (subject to a few limitations --
see <<sec-calling-convention>>). Since externs are architecture-specific and
their behavior is known to the architecture definition, these annotations are
not strictly necessary (an implementation can have knowledge of how externs
interact based on their names built into it), but these annotations provide a
uniform way of describing certain well-defined interactions (or their absence),
allowing architecture-independent analysis of P4 programs.

// 1210
* `@pure` - Describes a function that depends solely on its `in` parameter
  values, and has no effect other than returning a value, and copy-out behavior
  on its `out` and `inout` parameters. No hidden state is recorded between calls,
  and its value does not depend on any hidden state that may be changed by other
  calls. An example is a `hash` function that computes a deterministic hash of
  its arguments, and its return value does not depend upon any control-plane
  writable seed or initialization vector value. A `@pure` function whose results
  are unused may be safely eliminated with no adverse effects, and multiple calls
  with identical arguments may be combined into a single call (subject to the
  limits imposed by copy-out behavior of `out` and `inout` parameters). `@pure`
  functions may also be reordered with respect to other computations that are not
  data dependent.
* `@noSideEffects` - Weaker than `@pure` and describes a function that does not
  change any hidden state, but may depend on hidden state. One example is a
  `hash` function that computes a deterministic hash of its arguments, plus some
  internal state that can be modified via control plane API calls such as a seed
  or initialization vector. Another example is a read of one element of a
  register array extern object.  Such a function may be dead code eliminated, and
  may be reordered or combined with other `@noSideEffects` or `@pure` calls
  (subject to the limits imposed by copy-out behavior of `out` and `inout`
  parameters), but not with other function calls that may have side effects that
  affect the function.

// Added
ifndef::release[]
NOTE: `@pure` and `@noSideEffects` are currently unimplemented in P4-SpecTec.
endif::[]

[#sec-deprecated-anno]
==== Deprecated annotation

// 1211
The `deprecated` annotation has a required string argument that is a message
that will be printed by a compiler when a program is using the deprecated
construct. This is mostly useful for annotating library constructs, such as
externs. The parameter must be a local compile-time known value of type
`string`.

// 1212
[source,p4]
----
#define DEPR_V1_2_2 "Deprecated in v1.2.2"
@deprecated("Please use the 'check' function instead." ++ DEPR_V1_2_2)
extern Checker {
   /* body omitted */
}
----

[#sec-nowarn-anno]
==== No warnings annotation

// 1213
The `noWarn` annotation has a required string argument that indicates a
compiler warning that will be inhibited. For example `@noWarn("unused")` on a
declaration will prevent a compiler warning if that declaration is not used.
The parameter must be a local compile-time known value of type `string`.
