[#sec-control-local-declaration]
=== Control local declarations

Control local declarations are defined as follows:

${syntax: controlLocalDeclaration controlLocalDeclarationList}

==== Semantics of parser local declarations

===== Type checking

// Added
${relation-title-source: ControlLocalDecl_ok}
${relation-title-prose: ControlLocalDecl_ok}

// Added
After type checking, control local declarations are represented in P4~IR~ as
follows:

// Added
${syntax: controlLocalDeclarationIR}

// Added
A list of control local declarations is type checked by:

// Added
${relation-title-source: ControlLocalDeclList_ok}
${relation-title-prose: ControlLocalDeclList_ok}

// Added
${rulegroup-source: ControlLocalDeclList_ok}
${rulegroup-prose: ControlLocalDeclList_ok}

// Added
${relation-title-source: ControlLocalDecls_ok}
${relation-title-prose: ControlLocalDecls_ok}

// Added
${rulegroup-source: ControlLocalDecls_ok}
${rulegroup-prose: ControlLocalDecls_ok}

===== Compile-time evaluation

// Added
${relation-title-source: ControlLocalDecl_inst}
${relation-title-prose: ControlLocalDecl_inst}

// Added
A list of control local declarations is compile-time evaluated by:

// Added
${relation-title-source: ControlLocalDecls_inst}
${relation-title-prose: ControlLocalDecls_inst}

// Added
${rulegroup-source: ControlLocalDecls_inst}
${rulegroup-prose: ControlLocalDecls_inst}

===== Runtime evaluation

// Added
${relation-title-source: ControlLocalDecl_eval}
${relation-title-prose: ControlLocalDecl_eval}

// Added
Evaluation of a control local declaration yields:

${syntax: controlLocalDeclarationResult
          continueEmptyResult exitResult}

// Added
A list of control local declarations is runtime evaluated by:

// Added
${relation-title-source: ControlLocalDecls_eval}
${relation-title-prose: ControlLocalDecls_eval}

// Added
${rulegroup-source: ControlLocalDecls_eval}
${rulegroup-prose: ControlLocalDecls_eval}

// Added
The subsequent sections describe each kind of declaration in detail. `table`
declarations are special and are separately described in
<<sec-match-action-table>>.

==== Constant declarations

// Added
See <<sec-constant-declaration>> for general information about constant
declarations.

===== Type checking

// Added
${rulegroup-source: ControlLocalDecl_ok/constantDeclaration}
${rulegroup-prose: ControlLocalDecl_ok/constantDeclaration}

===== Compile-time evaluation

// Added
${rulegroup-source: ControlLocalDecl_inst/constantDeclarationIR}
${rulegroup-prose: ControlLocalDecl_inst/constantDeclarationIR}

===== Runtime evaluation

// Added
${rulegroup-source: ControlLocalDecl_eval/constantDeclarationIR}
${rulegroup-prose: ControlLocalDecl_eval/constantDeclarationIR}

==== Instantiations

// Added
See <<sec-instantiation-declaration>> for general information about instantiations.

===== Type checking

// Added
${rulegroup-source: ControlLocalDecl_ok/instantiation}
${rulegroup-prose: ControlLocalDecl_ok/instantiation}

===== Compile-time evaluation

// Added
${rulegroup-source: ControlLocalDecl_inst/instantiationIR}
${rulegroup-prose: ControlLocalDecl_inst/instantiationIR}

==== Variable declarations

// Added
See <<sec-variable-declaration>> for general information about variable
declarations.

===== Type checking

// Added
${rulegroup-source: ControlLocalDecl_ok/variableDeclaration}
${rulegroup-prose: ControlLocalDecl_ok/variableDeclaration}

===== Compile-time evaluation

// Added
${rulegroup-source: ControlLocalDecl_inst/variableDeclarationIR}
${rulegroup-prose: ControlLocalDecl_inst/variableDeclarationIR}

===== Runtime evaluation

// Added
${rulegroup-source: ControlLocalDecl_eval/variableDeclarationIR}
${rulegroup-prose: ControlLocalDecl_eval/variableDeclarationIR}

==== Action declarations

// Added
See <<sec-action-declaration>> for general information about action
declarations.

===== Type checking

// Added
${rulegroup-source: ControlLocalDecl_ok/actionDeclaration}
${rulegroup-prose: ControlLocalDecl_ok/actionDeclaration}

===== Compile-time evaluation

// Added
${rulegroup-source: ControlLocalDecl_inst/actionDeclarationIR}
${rulegroup-prose: ControlLocalDecl_inst/actionDeclarationIR}
