[#sec-table-additional]
==== Additional properties

// 978
A `table` declaration defines its essential control and data plane
interfaces--i.e., keys and actions. However, the best way to implement a table
may actually depend on the nature of the entries that will be installed at
runtime (for example, tables could be dense or sparse, could be implemented as
hash-tables, associative memories, tries, etc.) In addition, some architectures
may support extra table properties whose semantics lies outside the scope of
this specification. For example, in architectures where table resources are
statically allocated, programmers may be required to define a `size` table
property, which can be used by the compiler back-end to allocate storage
resources. However, these architecture-specific properties may not change the
semantics of table lookups, which always produce either a `hit` and an action
or a `miss`--they can only change how those results are interpreted on the
state of the data plane. This restriction is needed to ensure that it is
possible to reason about the behavior of tables during compilation.

// 979
As another example, an `implementation` property could be used to pass
additional information to the compiler back-end. The value of this property
could be an instance of an `extern` block chosen from a suitable library of
components. For example, the core functionality of the P4~14~ table
`action_profile` constructs could be implemented on architectures that support
this feature using a construct such as the following:

// 980
[source,p4]
----
extern ActionProfile {
   ActionProfile(bit<32> size); // number of distinct actions expected
}
table t {
    key = { /* body omitted */ }
    size = 1024;
    implementation = ActionProfile(32);  // constructor invocation
}
----

// 981
Here the action profile might be used to optimize for the case where the table
has a large number of entries, but the actions associated with those entries
are expected to range over a small number of distinct values. Introducing a
layer of indirection enables sharing identical entries, which can significantly
reduce the table's storage requirements.

===== Type checking

// Added
Additional properties, including `size`, is type checked as follows:

// Added
${rulegroup-source: TableProperty_ok/size-and-others}
${rulegroup-prose: TableProperty_ok/size-and-others}

// Added
After type checking, these are represented in P4~IR~ as:

// Added
${syntax: tableCustomPropertyIR}

===== Compile-time evaluation

// Added
${rulegroup-source: TableProperty_inst/tableCustomPropertyIR}
${rulegroup-prose: TableProperty_inst/tableCustomPropertyIR}
