[#sec-assignment-statement]
=== Assignment statements

// Added
${syntax: assignop assignmentStatement}

// 700
An assignment, written with the `=` sign, first evaluates its left
sub-expression to an l-value, then evaluates its right sub-expression to a
value, and finally copies the value into the l-value. Derived types (e.g.
``struct``s) are copied recursively, and all components of ``header``s are
copied, including validity bits. Assignment is not defined for `extern`
values.

// 701
An assignment may also be written with a binary arithmetic or bit manipulation
operator immediately before the `=` sign. This performs the binary operator on
the old value of the left sub-expression and the right sub-expression and
assigns the result to the l-value. Thus an assignment like `A += B` is
equivalent to `A = A + B`, except that `A` is only evaluated once.  This means
that any side-effects within this operand (eg, a function call inside an array
index or slice expression) only occur once. This is not valid for comparison
operators, logical operators, concat, range, or mask operators.

==== Type checking

// Added
After type checking, an assignment statement has the form:

// Added
${syntax: assignmentStatementIR}

// Added
${rulegroup-source: Stmt_ok/assignmentStatement}
${rulegroup-prose: Stmt_ok/assignmentStatement}

==== Compile-time evaluation

// Added
${rulegroup-source: Stmt_inst/assignmentStatementIR}
${rulegroup-prose: Stmt_inst/assignmentStatementIR}

==== Runtime evaluation

// Added
${rulegroup-source: Stmt_eval/assignmentStatementIR}
${rulegroup-prose: Stmt_eval/assignmentStatementIR}
