[#sec-return-statement]
=== Return statements

// 706
The `return` statement immediately terminates the execution of the `action`,
`function` or `control` containing it. `return` statements are not allowed
within parsers. `return` statements followed by an expression are only allowed
within functions that return values; in this case the type of the expression
must match the return type of the function.  Any copy-out behavior due to
direction `out` or `inout` parameters of the enclosing `action`, `function`, or
`control` are still performed after the execution of the `return` statement.
See <<sec-call-convention>> for details on copy-out behavior.

// 707 - Modified
${syntax: returnStatement}

==== Type checking

// Added
After type checking, a `return` statement has the form:

// Added
${syntax: returnStatementIR}

// Added
${rulegroup-source: Stmt_ok/returnStatement}
${rulegroup-prose: Stmt_ok/returnStatement}

==== Compile-time evaluation

// Added
${rulegroup-source: Stmt_inst/returnStatementIR}
${rulegroup-prose: Stmt_inst/returnStatementIR}

==== Runtime evaluation

// Added
${rulegroup-source: Stmt_eval/returnStatementIR}
${rulegroup-prose: Stmt_eval/returnStatementIR}
