[#sec-switch-statement]
=== Switch statements

// 720
The `switch` statement can only be used within `control` blocks, `action`
bodies, or function bodies.

// 721 - Modified
${syntax: switchStatement
          switchCaseList
          switchCase
          switchLabel}

// 722
The `expressionNonBrace` is the same as `expression` as defined in
<<sec-expression>>, except it does not include any cases that can begin with a
left brace `{` character, to avoid syntactic ambiguity with a block statement.

// 723
There are two kinds of `switch` expressions allowed, described separately in
the following two subsections.

==== Notes common to all switch statements

// 731
It is a compile-time error if two labels of a `switch` statement equal each
other. The switch label values need not include all possible values of the
switch expression. It is optional to have a `switch` case with the `default`
label, but if one is present, it must be the last one in the `switch`
statement.

// 732
If a switch label is not followed by a block statement, it falls through to the
next label. However, if a block statement is present, it does not fall through.
Note that this is different from C-style `switch` statements, where a `break`
is needed to prevent fall-through. If the last switch label is not followed by
a block statement, the behavior is the same as if the last switch label were
followed by an empty block statement `{ }`.

// 733
When a `switch` statement is executed, first the switch expression is
evaluated, and any side effects from evaluating this expression are visible to
any `switch` case that is executed. Among switch labels that are not `default`,
at most one of them can equal the value of the switch expression. If one is
equal, that switch case is executed.

// 734
If no labels are equal to the `switch` expression, then:

// 735
* if there is a `default` label, the case with the `default` label is
  executed.
* if there is no `default` label, then no switch case is executed, and
  execution continues after the end of the `switch` statement, with no side
  effects (except any that were caused by evaluating the `switch` expression).

// 736
See "Implementing generalized P4_16 switch statements" for possible techniques
that one might use to implement generalized switch
statements.footnote:GeneralizedSwitchStatements[<https://github.com/p4lang/p4-spec/blob/master/p4-16/spec/docs/implementing-generalized-switch-statements.md>]

[#sec-switch-statement-table]
==== Switch statement on match-action table result

// 724
This type of `switch` statement can only be used within control `apply` blocks.
For this variant of `switch` statement, the expression must be of the form
`t.apply().action_run`, where `t` is the name of a table (see
<<sec-match-action-table-invocation>>). All switch labels must be names of
actions of the table `t`, or `default`.

// 725
[source,p4]
----
switch (t.apply().action_run) {
   action1:                         // fall-through to action2:
   action2: { /* body omitted */ }
   action3: { /* body omitted */ }  // no fall-through from action2 to action3 labels
   default: { /* body omitted */ }
}
----

// 726
Note that the `default` label of the `switch` statement is used to match on the
kind of action executed, no matter whether there was a table hit or miss. The
`default` label does not indicate that the table missed and the
`default_action` was executed.

===== Type checking

// Added
${rulegroup-source: Stmt_ok/switchStatement-table}
${rulegroup-prose: Stmt_ok/switchStatement-table}

// Added
Switch cases are type checked with the relation:

// Added
${relation-title-source: SwitchCaseList_table_ok}
${relation-title-prose: SwitchCaseList_table_ok}

// Added
A switch case is type checked with:

// Added
${relation-title-source: SwitchCase_table_ok}
${relation-title-prose: SwitchCase_table_ok}

// Added
${rulegroup-source: SwitchCase_table_ok}
${rulegroup-prose: SwitchCase_table_ok}

// Added
A switch label is type checked with:

// Added
${relation-title-source: SwitchLabel_table_ok}
${relation-title-prose: SwitchLabel_table_ok}

// Added
${rulegroup-source: SwitchLabel_table_ok}
${rulegroup-prose: SwitchLabel_table_ok}

[#sec-switch-statement-table-compile-time-evaluation]
===== Compile-time evaluation

// Added
${rulegroup-source: Stmt_inst/switchStatementIR}
${rulegroup-prose: Stmt_inst/switchStatementIR}

// Added
The compile-time evaluation of switch cases is defined with the relation:

// Added
${relation-title-source: SwitchCases_inst}
${relation-title-prose: SwitchCases_inst}

// Added
A switch case is compile-time evaluated with:

// Added
${relation-title-source: SwitchCase_inst}
${relation-title-prose: SwitchCase_inst}

// Added
${rulegroup-source: SwitchCase_inst}
${rulegroup-prose: SwitchCase_inst}

===== Runtime evaluation

// Added
${rulegroup-source: Stmt_eval/switchStatementIR-table}
${rulegroup-prose: Stmt_eval/switchStatementIR-table}

// Added
Switch cases are runtime evaluated with the relation:

// Added
${relation-title-source: SwitchCases_table_eval}
${relation-title-prose: SwitchCases_table_eval}

// Added
${rulegroup-source: SwitchCases_table_eval}
${rulegroup-prose: SwitchCases_table_eval}

[#sec-switch-statement-general]
==== Switch statement on numeric or enumerated type

// 727
For this variant of `switch` statement, the expression must evaluate to a
result with one of these types:

// 728
* `bit<W>`
* `int<W>`
* `enum`, either with or without an underlying representation specified
* `error`

// 729
All switch labels must be expressions with compile-time known values, and must
have a type that can be implicitly cast to the type of the `switch` expression
(see <<sec-implicit-casts>>). Switch labels must not begin with a left brace
character `{`, to avoid ambiguity with a block statement.

// 730
[source,p4]
----
// Assume the expression hdr.ethernet.etherType has type bit<16>.
switch (hdr.ethernet.etherType) {
   0x86dd: { /* body omitted */ }
   0x0800: // fall-through to the next body
   0x0802: { /* body omitted */ }
   0xcafe: { /* body omitted */ }
   default: { /* body omitted */ }
}
----

===== Type checking

// Added
${rulegroup-source: Stmt_ok/switchStatement-general}
${rulegroup-prose: Stmt_ok/switchStatement-general}

// Added
Switch cases are type checked with the relation:

// Added
${relation-title-source: SwitchCaseList_general_ok}
${relation-title-prose: SwitchCaseList_general_ok}

// Added
A switch case is type checked with:

// Added
${relation-title-source: SwitchCase_general_ok}
${relation-title-prose: SwitchCase_general_ok}

// Added
${rulegroup-source: SwitchCase_general_ok}
${rulegroup-prose: SwitchCase_general_ok}

// Added
A switch label is type checked with:

// Added
${relation-title-source: SwitchLabel_general_ok}
${relation-title-prose: SwitchLabel_general_ok}

// Added
${rulegroup-source: SwitchLabel_general_ok}
${rulegroup-prose: SwitchLabel_general_ok}

===== Compile-time evaluation

// Added
See <<sec-switch-statement-table-compile-time-evaluation>>.

===== Runtime evaluation

// Added
${rulegroup-source: Stmt_eval/switchStatementIR-general}
${rulegroup-prose: Stmt_eval/switchStatementIR-general}

// Added
Switch cases are runtime evaluated with the relation:

// Added
${relation-title-source: SwitchCases_general_eval}
${relation-title-prose: SwitchCases_general_eval}

// Added
${rulegroup-source: SwitchCases_general_eval}
${rulegroup-prose: SwitchCases_general_eval}

// Added
A switch label is runtime evaluated with:

// Added
${relation-title-source: SwitchLabel_general_eval}
${relation-title-prose: SwitchLabel_general_eval}

// Added
${rulegroup-source: SwitchLabel_general_eval}
${rulegroup-prose: SwitchLabel_general_eval}
