[#sec-object]
=== Objects

// Added
``table``s, ``value_set``s, and ``extern`` objects are stateful entities in P4
programs. These objects should be instantiated statically prior to program
execution. ``parser``s, ``control``s, and ``package``s may contain stateful
objects, thus they must also be instantiated.

// Added
The runtime representation of these objects is defined as follows:

// Added
${syntax: object}

// Added
The instantiation phase (described in <<sec-instantiation>>) creates objects in
the source P4 program, and allocates them in the global store. At runtime
(described in <<sec-runtime-evaluation>>), these objects interact, as defined
by the target architecture, to process packets.

[#sec-fully-qualified-names]
==== Fully-qualified names

// Added
Instantiation may create multiple instances of a type, each of which must
have a unique, fully-qualified name. Thus, objects are identified by their
full-qualified names (``objectId``). <<sec-control-plane-names>> describes
how a fully-qualified name is constructed.

// Added
${syntax: objectId}
