[#sec-parser-object]
=== Parser objects

// 747
A parser declaration comprises a name, a list of parameters, an optional list
of constructor parameters, local elements, and parser states (as well as
optional annotations).

// 748 - Modified
${syntax: parserDeclaration parserLocalDeclaration parserState}

// 753
At least one state, named `start`, must be present in any `parser`. A parser
may not define two states with the same name. It is also illegal for a parser
to give explicit definitions for the `accept` and `reject` states--those
states are logically distinct from the states defined by the programmer.

// 754 - Modified
Preceding the parser states, a `parser` may also contain a list of local
elements. These can be constants, variables, or instantiations of objects that
may be used within the parser. Such objects may be instantiations of `extern`
objects, or other ``parser``s that may be invoked as subroutines. However, it
is illegal to instantiate a `control` block within a `parser`.

// 756
The states and local elements are all in the same namespace, thus the following
example will produce an error:

// 757
[source,p4]
----
// erroneous example
parser p() {
    bit<4> t;
    state start {
       t = 1;
       transition t;
    }
    state t {  // error: name t is duplicated
       transition accept;
    }
}
----

// 758
For an example containing a complete declaration of a parser see
<<sec-vss-all>>.

// Added
A `parser` declaration introduces a parser object constructor, represented
as:

// Added
${syntax: parserObjectConstructorDef}

// Added
Parser objects are then instantiated by constructor invocations to yield:

// Added
${syntax: parserObject}

==== Well-formedness

// Added
${rulegroup-source: ConstructorType_wf/parserObjectTypeIR}
${rulegroup-prose: ConstructorType_wf/parserObjectTypeIR}

==== Instantiation

// Added
${rulegroup-source: Constructor_call/parserConstructorDef}
${rulegroup-prose: Constructor_call/parserConstructorDef}
