[#sec-explicit-cast]
=== Explicit casts

// Added
The below relation checks whether a type can be explicitly cast to another
type.

// Added
${relation-title-source: Cast_expl}
${relation-title-prose: Cast_expl}

// Added
First, the two types are unrolled and checked to see if they are the same type.
If so, no cast is needed.

// Added
${rulegroup-source: Cast_expl}
${rulegroup-prose: Cast_expl}

// Added
If the two types are not equal, the below relation is applied.

// Added
${relation-title-source: Cast_expl_neq}
${relation-title-prose: Cast_expl_neq}

[discrete]
====== Cast from `bool` to `bit<1>`

${rulegroup-source: Cast_expl_neq/boolean-fixBit}
${rulegroup-prose: Cast_expl_neq/boolean-fixBit}

[discrete]
====== Cast from `int` to `bool`, `int<S>`, or `bit<W>`

${rulegroup-source: Cast_expl_neq/arbitraryInt}
${rulegroup-prose: Cast_expl_neq/arbitraryInt}

[discrete]
====== Cast from `int<S>` to `int`, `int<T>`, or `bit<W>`

${rulegroup-source: Cast_expl_neq/fixInt}
${rulegroup-prose: Cast_expl_neq/fixInt}

[discrete]
====== Cast from `bit<W>` to `bool`, `int`, `int<S>`, or `bit<X>`

${rulegroup-source: Cast_expl_neq/fixBit}
${rulegroup-prose: Cast_expl_neq/fixBit}

[discrete]
====== Cast from a new type to its underlying type, and vice versa

${rulegroup-source: Cast_expl_neq/newTypeIR}
${rulegroup-prose: Cast_expl_neq/newTypeIR}

[discrete]
====== Cast from an enum with an underlying type to the underlying type, and vice versa

${rulegroup-source: Cast_expl_neq/enumTypeIR-serializable}
${rulegroup-prose: Cast_expl_neq/enumTypeIR-serializable}

[discrete]
====== Cast from a default type to the target type

${rulegroup-source: Cast_expl_neq/defaultTypeIR}
${rulegroup-prose: Cast_expl_neq/defaultTypeIR}

[discrete]
====== Cast from an invalid header type to a header or header union type

${rulegroup-source: Cast_expl_neq/invalidHeaderTypeIR}
${rulegroup-prose: Cast_expl_neq/invalidHeaderTypeIR}

[discrete]
====== Cast from a sequence type to a list, tuple, header stack, struct, header, or another sequence type

// Added
${rulegroup-source: Cast_expl_neq/sequenceTypeIR-non-default}
${rulegroup-prose: Cast_expl_neq/sequenceTypeIR-non-default}

[discrete]
====== Cast from a sequence type with default initializer to a tuple, header stack, struct, or header type

// Added
${rulegroup-source: Cast_expl_neq/sequenceTypeIR-default}
${rulegroup-prose: Cast_expl_neq/sequenceTypeIR-default}

[discrete]
====== Cast from a record type to a struct or header type

// Added
${rulegroup-source: Cast_expl_neq/recordTypeIR-non-default}
${rulegroup-prose: Cast_expl_neq/recordTypeIR-non-default}

[discrete]
====== Cast from a record type with default initializer to a struct or header type

// Added
${rulegroup-source: Cast_expl_neq/recordTypeIR-default}
${rulegroup-prose: Cast_expl_neq/recordTypeIR-default}
