[#sec-cast-operation]
=== Performing casts

// Added
Cast operations are evaluated with:

// Added
${func-title-source: cast_op}
${func-title-prose: cast_op}

// Added
${func-source: cast_op}
${func-prose: cast_op}

[discrete]
====== From a `bool` value

// Added
${func-source: cast_bool}
${func-prose: cast_bool}

[discrete]
====== From an integer value

// Added
${func-source: cast_int}
${func-prose: cast_int}

[discrete]
====== From an error value

// Added
${func-source: cast_error}
${func-prose: cast_error}

[discrete]
====== From a list value

// Added
${func-source: cast_list}
${func-prose: cast_list}

[discrete]
====== From a header stack value

// Added
${func-source: cast_header_stack}
${func-prose: cast_header_stack}

[discrete]
====== From a struct value

// Added
${func-source: cast_struct}
${func-prose: cast_struct}

[discrete]
====== From a header value

// Added
${func-source: cast_header}
${func-prose: cast_header}

[discrete]
====== From an enum value

// Added
${func-source: cast_enum}
${func-prose: cast_enum}

[discrete]
====== From a default value

// Added
${func-source: cast_default}
${func-prose: cast_default}

[discrete]
====== From an invalid header value

// Added
${func-source: cast_invalid_header}
${func-prose: cast_invalid_header}

[discrete]
====== From a sequence value

// Added
${func-source: cast_sequence}
${func-prose: cast_sequence}

[discrete]
====== From a record value

// Added
${func-source: cast_record}
${func-prose: cast_record}

[discrete]
====== From a set value

// Added
${func-source: cast_set}
${func-prose: cast_set}
