[#sec-type-checking]
=== Type checking

// 186 - Modified
P4~16~ is a statically-typed language. Programs that do not pass the type
checker are considered invalid and rejected by the compiler. P4 provides a
number of base types as well as type operators that construct derived types.

[#sec-p4-ir]
==== P4 Intermediate Representation

// Added
P4~IR~ is an intermediate representation for P4 programs. P4~IR~ extends the
surface syntax of P4~16~ with additional information obtained during type
checking. They include:

// Added
* All expressions are annotated with their types.
* Implicit casts are made explicit.
* Omitted type arguments are inferred and made explicit.

// Added
P4~IR~ is designed to stay as close as possible to the surface syntax of P4~16~.
This makes it easy to relate P4~IR~ programs to their source P4~16~ programs.

// Added
Take expressions as an example.

// Added
${syntax: expression expressionIR expressionNoteIR typedExpressionIR}

// Added
`typedExpressionIR` is an intermediate representation of `expression` that is
annotated with type information, `expressionNoteIR`. Nevertheless, the
structure of the grammar mostly stays the same.

// Added
${syntax: binaryExpression binaryExpressionIR}

// Added
`binaryExpressionIR` is an intermediate representation of `binaryExpression`.
The only difference is that the operands are now of type `typedExpressionIR`.

// Added
ifndef::release[]
NOTE: Added explanation for P4~IR~. More explanation needed?
endif::[]

==== Typing a P4 program

// Added
For a well-typed P4~16~ program, `p4program`, a type checker produces a P4~IR~
program, `p4programIR`:

// Added
${syntax: p4programIR}

// Added
`Program_ok` type checks a `p4program` and produces a `p4programIR`.

// Added
${relation-title-source: Program_ok}
${relation-title-prose: Program_ok}

// Added
Below is a prose algorithm that implements `Program_ok`. Details of what each
meta-variable means are provided in the subsequent sections.

// Added
${rulegroup-source: Program_ok}
${rulegroup-prose: Program_ok}

// Added
The following helper function is used to collect ``declaration``s in a `p4program`:

// Added
${func-source: flatten_p4program}
${func-prose: flatten_p4program}

==== Typing context

// Added
${syntax: globalTypingLayer blockTypingLayer localTypingLayer typingContext}

// Added
A typing context is used to keep track of the types of all named declarations
in scope at a given program point. It consists of three layers:

// Added
* A global typing layer, which contains all declarations at the top level of a
  P4~16~ program.
* A block typing layer, which contains all declarations in the current block
  scope.
* A local typing layer, which contains all declarations in the current local
  scope.

// Added
Each layer contains mappings from names to types.

// Added
${syntax: varTypeIR typeFrame}

// Added
`typeFrame` is a map from variable names to their types, `varTypeIR`. In
addition to the type of the variable, `varTypeIR` also contains the direction
of the variable (`direction`), whether it is a compile-time constant (`ctk`),
and whether it is associated with a compile-time known value (`value?`).

// Added
The compile-time known-ness is discussed in <<sec-compile-time-known>>.

// Added
Notice that `localTypingLayer` contains multiple ``typeFrame``s. This is because a
local scope can be nested with block statements.

// Added
${syntax: typeDefIR typeDefEnv}

// Added
`typeDefEnv` is a map from type names to their type definitions, `typeDefIR`.
`typeDefIR` is a type constructor, derived from user-defined type declarations.

// Added
${syntax: callableTypeDefIR callableTypeDefEnv}

// Added
Functions, methods, and actions can be defined in P4~16~. These are
collectively called callables. `callableTypeDefEnv` is a map from callable
names to their type definitions, `callableTypeDefIR`.

// Added
${syntax: constructorTypeDefIR constructorTypeDefEnv}

// Added
Stateful objects can be defined in P4~16~, which are instantiated using
constructors. `constructorTypeDefEnv` is a map from constructor names to their
type definitions, `constructorTypeDefIR`.

// Added
ifndef::release[]
NOTE: Added explanation for the typing context. Is this the right place?
endif::[]
