[#sec-compile-time-known]
=== Compile-time known and local compile-time known values

// 1070
Certain expressions in a P4 program have the property that their value can be
determined at compile time. Moreover, for some of these expressions, their
value can be determined only using information in the current scope. We call
these _compile-time known values_ and _local compile-time known values_
respectively.

// 1071
The following are local compile-time known values:

// 1072 - Modified
- Integer literals, Boolean literals, and string literals.
- Identifiers declared as constants using the `const` keyword.
- Identifiers declared in an `error`, `enum`, or `match_kind` declaration.
- The `default` identifier.
- The `size` field of a value with type header stack.
- The `_` identifier when used as a `select` expression label.
- The expression `{#}` representing an invalid header or header union value.
// - Instances constructed by instance declarations and constructor invocations.
- Identifiers that represent declared types, actions, functions, tables, parsers, controls, or packages.
- Tuple expression where all components are local compile-time known values.
- Structure-valued expressions, where all fields are local compile-time known values.
- Expressions evaluating to a list type, where all elements are local compile-time known values.
- Legal casts applied to local compile-time known values.
- Indexing a local compile-time known stack or tuple value with a local compile-time known index.
- Accessing a field of a local compile-time known struct, header, or header union value.
- The following expressions (`{plus}`, `-`, `|{plus}|`, `|-|`, `*`, `/`, `%`, `!`, `&`, `|`, `^`,
  `&&`, `||`, `<<`, `>>`, `~`, `>`, `<`, `==`, `!=`, `\<=`, `>=`, `++`, `[:]`, `?:`)
  when their operands are all local compile-time known values.
- Expressions of the form `e.minSizeInBits()`, `e.minSizeInBytes()`,
  `e.maxSizeInBits()` and `e.maxSizeInBytes()` where the type of `e` is not
  generic.

ifndef::release[]
NOTE: It is questionable whether instances constructed by instance declarations
and constructor invocations should be considered local compile-time known
values. So, the corresponding bullet is commented out in this document.
A related spec issue is made here: https://github.com/p4lang/p4-spec/issues/1309.
endif::[]

// 1073
The following are compile-time known values:

// 1074
- All local compile-time known values.
- Constructor parameters (i.e., the declared parameters for a `parser`, `control`, etc.)
- Tuple expression where all components are compile-time known values.
- Structure-valued expressions, where all fields are compile-time known values.
- Expressions evaluating to a list type, where all elements are compile-time known values.
- Legal casts applied to compile-time known values.
- Indexing a compile-time known stack or tuple value with a compile-time known index.
- Accessing a field of a compile-time known struct, header, or header union value.
- The following expressions (`{plus}`, `-`, `|{plus}|`, `|-|`, `*`, `/`, `%`, `!`, `&`, `|`, `^`,
  `&&`, `||`, `<<`, `>>`, `~`, `>`, `<`, `==`, `!=`, `\<=`, `>=`, `++`, `[:]`, `?:`)
  when their operands are all compile-time known values.
- Expressions of the form `e.minSizeInBits()`, `e.minSizeInBytes()`,
  `e.maxSizeInBits()` and `e.maxSizeInBytes()` where the the type of `e` is
  generic.

// 1075
Intuitively, the main difference between _compile-time known values_ and _local
compile-time known values_ is that the former also contains constructor
parameters. The distinction is important when it comes to defining the meaning
of features like types. For example, in the type `bit<e>`, the expression `e`
must be a local compile-time known value. Suppose instead that `e` were a
constructor parameter--i.e., merely a compile-time known value. In this
situation, it would be impossible to resolve `bit<e>` to a concrete type using
purely local information--we would have to wait until the constructor was
instantiated and the value of `e` known.

// Added
Local compile-time known values can be identified in the type checking phase.
Compile-time known values can be identified after type checking, during the
instantiation phase. Once the constructor parameters are bound to actual
arguments and type parameters are bound to actual types, compile-time known
values can be evaluated to concrete values.

// Added
`ctk` is a marker used in P4~IR~ to indicate whether an expression is local
compile-time known, compile-time known, or neither.

// Added
${syntax: ctk}

// Added
``typedExpressionIR``s in P4~IR~, produced by typing ``expression``s in P4~16~,
annotated with their type ``typeIR`` and a ``ctk`` marker indicating the
compile-time known status.

// Added
${syntax: expressionNoteIR typedExpressionIR}
