[#sec-reference-expression]
=== Reference expressions

// Added
A reference expression is an expression that refers to a named entity in a P4
program:

// Added
${syntax: referenceExpression prefixedNonTypeName}

// Added
References are resolved according to the scoping rules of P4 (see
<<sec-scoping>>).

==== Type checking

// Added
After type checking, a reference expression is represented in P4~IR~ as:

// Added
${syntax: referenceExpressionIR}

// Added
${rulegroup-source: Expr_ok/referenceExpression}
${rulegroup-prose: Expr_ok/referenceExpression}

// Added
A variable is looked up in the typing context with:

// Added
${func-source: find_var_t}
${func-prose: find_var_t}

==== Local compile-time evaluation

// Added
${rulegroup-source: Expr_eval_lctk/referenceExpressionIR}
${rulegroup-prose: Expr_eval_lctk/referenceExpressionIR}

==== Compile-time evaluation

// Added
${rulegroup-source: Expr_inst/referenceExpressionIR}
${rulegroup-prose: Expr_inst/referenceExpressionIR}

// Added
A variable is looked up in the instantiation context with:

// Added
${func-source: find_var_i}
${func-prose: find_var_i}

==== Runtime evaluation

// Added
${rulegroup-source: Expr_eval/referenceExpressionIR}
${rulegroup-prose: Expr_eval/referenceExpressionIR}

// Added
A variable is looked up in the runtime context with:

// Added
${func-source: find_var_e}
${func-prose: find_var_e}
