[#sec-unary-expression]
=== Unary expressions

${syntax: unaryExpression unop}

See <<sec-unary-operation>> for details on how each unary operator is
evaluated.

==== Type checking

After type checking, unary expressions have the form:

${syntax: unaryExpressionIR}

===== Negation

${rulegroup-source: Expr_ok/unaryExpression-lnot}
${rulegroup-prose: Expr_ok/unaryExpression-lnot}

===== Bitwise complement

${rulegroup-source: Expr_ok/unaryExpression-bnot}
${rulegroup-prose: Expr_ok/unaryExpression-bnot}

===== Plus and minus

${rulegroup-source: Expr_ok/unaryExpression-uplusminus}
${rulegroup-prose: Expr_ok/unaryExpression-uplusminus}

==== Local compile-time evaluation

${rulegroup-source: Expr_eval_lctk/unaryExpressionIR}
${rulegroup-prose: Expr_eval_lctk/unaryExpressionIR}

==== Compile-time evaluation

${rulegroup-source: Expr_inst/unaryExpressionIR}
${rulegroup-prose: Expr_inst/unaryExpressionIR}

==== Runtime evaluation

${rulegroup-source: Expr_eval/unaryExpressionIR}
${rulegroup-prose: Expr_eval/unaryExpressionIR}
