[#sec-ternary-expression]
=== Ternary expressions

// 430
A conditional expression of the form `e1 ? e2 : e3` behaves the same as in
languages like C. As described above, the expression `e1` is evaluated first,
and second either `e2` or `e3` is evaluated depending on the result.

// 431
The first sub-expression `e1` must have Boolean type and the second and third
sub-expressions must have the same type, which cannot both be
arbitrary-precision integers unless the condition itself can be evaluated at
compilation time. This restriction is designed to ensure that the width of the
result of the conditional expression can be inferred statically at compile
time.

// Added
${syntax: ternaryExpression}

==== Type checking

// Added
After type checking, ternary expressions have the form:

// Added
${syntax: ternaryExpressionIR}

// Added
${rulegroup-source: Expr_ok/ternaryExpression}
${rulegroup-prose: Expr_ok/ternaryExpression}

==== Local compile-time evaluation

// Added
${rulegroup-source: Expr_eval_lctk/ternaryExpressionIR}
${rulegroup-prose: Expr_eval_lctk/ternaryExpressionIR}

==== Compile-time evaluation

// Added
${rulegroup-source: Expr_inst/ternaryExpressionIR}
${rulegroup-prose: Expr_inst/ternaryExpressionIR}

==== Runtime evaluation

// Added
${rulegroup-source: Expr_eval/ternaryExpressionIR}
${rulegroup-prose: Expr_eval/ternaryExpressionIR}
