[#sec-member-access-expression]
=== Member access expressions

// Added
A member access expression accesses a user-defined or built-in field in an
aggregate value. Also, it may access an element defined in an enum declaration.

// Added
${syntax: memberAccessExpression memberAccessBase}

==== Type checking

// Added
After type checking, a member access expression is represented in P4~IR~ as:

// Added
${syntax: memberAccessExpressionIR memberAccessBaseIR}

[discrete]
===== Accessing an enum member

// Added
${rulegroup-source: Expr_ok/memberAccessExpression-type}
${rulegroup-prose: Expr_ok/memberAccessExpression-type}

[discrete]
===== Accessing an aggregate member

// Added
${rulegroup-source: Expr_ok/memberAccessExpression-expression}
${rulegroup-prose: Expr_ok/memberAccessExpression-expression}

==== Local compile-time evaluation

[discrete]
===== Accessing an enum member

// Added
${rulegroup-source: Expr_eval_lctk/memberAccessExpressionIR-type}
${rulegroup-prose: Expr_eval_lctk/memberAccessExpressionIR-type}

[discrete]
===== Accessing an aggregate member

// Added
${rulegroup-source: Expr_eval_lctk/memberAccessExpressionIR-typedExpressionIR}
${rulegroup-prose: Expr_eval_lctk/memberAccessExpressionIR-typedExpressionIR}

==== Compile-time evaluation

[discrete]
===== Accessing an enum member

// Added
${rulegroup-source: Expr_inst/memberAccessExpressionIR-type}
${rulegroup-prose: Expr_inst/memberAccessExpressionIR-type}

[discrete]
===== Accessing an aggregate member

// Added
${rulegroup-source: Expr_inst/memberAccessExpressionIR-typedExpressionIR}
${rulegroup-prose: Expr_inst/memberAccessExpressionIR-typedExpressionIR}

==== Runtime evaluation

[discrete]
===== Accessing an enum member

// Added
${rulegroup-source: Expr_eval/memberAccessExpressionIR-type}
${rulegroup-prose: Expr_eval/memberAccessExpressionIR-type}

[discrete]
===== Accessing an aggregate member

// Added
${rulegroup-source: Expr_eval/memberAccessExpressionIR-typedExpressionIR}
${rulegroup-prose: Expr_eval/memberAccessExpressionIR-typedExpressionIR}
