(lang dune 3.7)
(using menhir 2.0)
(using mdx 0.2)
(name p4spectec)

(generate_opam_files true)

(package
  (name p4spectec)
  (version 0.0.1)
  (synopsis "P4SpecTec: A language design framework for the P4 Programming Language")
  (depends
    bignum
    core
    core_unix))
