[#sec-stateful-elements]
=== Stateful elements

// 135
Most P4 constructs are stateless: given some inputs they produce a result that
solely depends on these inputs. There are only two stateful constructs that may
retain information across packets:

// 136
* ``table``s: Tables are read-only for the data plane, but their entries can be
  modified by the control-plane,
* `extern` objects: many objects have state that can be read and written by the
  control plane and data plane. All constructs from the P4~14~ language version
  that encapsulate state (e.g., counters, meters, registers) are represented
  using `extern` objects in P4~16~.

// 137
In P4 all stateful elements must be explicitly allocated at compilation-time
through the process called "instantiation".

// 138
In addition, ``parser``s, `control` blocks, and ``package``s may contain
stateful element instantiations. Thus, they are also treated as stateful
elements, even if they appear to contain no state, and must be instantiated
before they can be used. However, although they are stateful, ``table``s do not
need to be instantiated explicitly--declaring a `table` also creates an
instance of it. This convention is designed to support the common case, since
most tables are used just once. To have finer-grained control over when a
`table` is instantiated, a programmer can declare it within a `control`.

// 139
Recall the example in <<sec-vss-all>>: `TopParser`, `TopPipe`, `TopDeparser`,
`Checksum16`, and `Switch` are types. There are two instances of `Checksum16`,
one in `TopParser` and one in `TopDeparser`, both called `ck`. The `TopParser`,
`TopDeparser`, `TopPipe`, and `Switch` are instantiated at the end of the
program, in the declaration of the `main` instance object, which is an instance
of the `Switch` type (a `package`).
