=== Parameters

// Added
${syntax: direction parameter}

// Added
Callables can have parameters. Each parameter has a direction, a type, a
name, and an optional default value.

// Added
A parameter is internally represented as:

// Added
${syntax: parameterIR}

// Added
The high-level overview of parameters with respect to the copy in/copy out
calling convention is described in <<sec-call-convention-overview>>. Below are
the formal typing and well-formedness rules for parameters that implement the
restrictions described there.

==== Type checking

// Added
${relation-title-prose: Parameter_ok}

// Added
Typing a parameter produces a `parameterIR` if it is well-typed. A parameter
is well-typed when its type is well-formed and its default value (if any) has
the same type as the parameter type.

// Added
${rulegroup-source: Parameter_ok}
${rulegroup-prose: Parameter_ok}

==== Well-formedness

// Added
${relation-title-prose: ParameterType_wf}

// Added
A parameter type is well-formed when its type is well-formed. Also, the type
should not be a synthesized type. Types that can only be local compile-time
known or compile-time known (e.g., `int` type) must be directionless. A default
value can be specified for `in` or directionless parameters only.

${rulegroup-source: ParameterType_wf}
${rulegroup-prose: ParameterType_wf}
