=== Call targets

// Added
Calls are composed of three components: the call target, type arguments, and
arguments. Call target identifies what is being called. It may be a callable
(actions, functions, and methods) or a constructor.

// Added
When calls are made from an expression, the call target is as follows:

// Added
${syntax: callExpression callTarget callableTarget constructorTarget}

// Added
When calls are made from a statement, the call target is as follows:

// Added
${syntax: lvalue callStatement directApplicationStatement}

// Added
And when calls are made from instantiation declarations, the call target is as follows:

// Added
${syntax: instantiation}

// Added
After type checking, call targets are represented as follows:

// Added
${syntax: callableTargetIR constructorTargetIR}

// Added
Thus, calls are represented as:

// Added
${syntax: callExpressionIR callStatementIR directApplicationStatementIR instantiationIR}

// Added
The following relation is used to check callable targets:

// Added
${relation-title-source: CallableTarget_ok}
${relation-title-prose: CallableTarget_ok}

// Added
${rulegroup-source: CallableTarget_ok}
${rulegroup-prose: CallableTarget_ok}

// Added
When a l-value is used as a callable target, the following relation is used to
check it:

// Added
${relation-title-source: CallableTarget_lvalue_ok}
${relation-title-prose: CallableTarget_lvalue_ok}

// Added
${rulegroup-source: CallableTarget_lvalue_ok}
${rulegroup-prose: CallableTarget_lvalue_ok}
