[#sec-callee-resolution]
=== Callee resolution

// Added
Given a call target, type arguments, and arguments, the callee should be
resolved. This is done both during type checking and runtime evaluation.

==== Resolving constructors

// Added
When type checking, constructors are resolved by:

// Added
${relation-title-source: ConstructorType_ok}
${relation-title-prose: ConstructorType_ok}

// Added
${rulegroup-source: ConstructorType_ok}
${rulegroup-prose: ConstructorType_ok}

// Added
During compile-time evaluation, constructors are resolved by:

// Added
${relation-title-source: Constructor_inst}
${relation-title-prose: Constructor_inst}

// Added
${rulegroup-source: Constructor_inst}
${rulegroup-prose: Constructor_inst}

==== Resolving callables

// Added
When type checking, callables are resolved by:

// Added
${relation-title-source: CallableType_ok}
${relation-title-prose: CallableType_ok}

// Added
At runtime, callables are resolved to callees by:

// Added
${relation-title-source: Callee_eval}
${relation-title-prose: Callee_eval}

// Added
While resolving callees, `exit;` statements may be encountered. Thus, the
result of callee resolution is:

// Added
${syntax: calleeResult}

// Added
The following subsections describe the two phases, for each kind of callable.

===== Actions

// Added
During type checking, actions are resolved by:

// Added
${syntax: actionTypeIR}

// Added
${rulegroup-source: CallableType_ok/actionTypeIR}
${rulegroup-prose: CallableType_ok/actionTypeIR}

// Added
During runtime evaluation, actions are resolved by:

// Added
${syntax: actionCallee}

// Added
${rulegroup-source: Callee_eval/actionCallee}
${rulegroup-prose: Callee_eval/actionCallee}

===== Functions

// Added
During type checking, functions are resolved by:

// Added
${syntax: functionTypeIR}

// Added
${rulegroup-source: CallableType_ok/functionTypeIR}
${rulegroup-prose: CallableType_ok/functionTypeIR}

// Added
During runtime evaluation, functions are resolved by:

// Added
${syntax: functionCallee}

// Added
For extern functions,

// Added
${rulegroup-source: Callee_eval/externFunctionCallee}
${rulegroup-prose: Callee_eval/externFunctionCallee}

// Added
For user-defined functions,

// Added
${rulegroup-source: Callee_eval/definedFunctionCallee}
${rulegroup-prose: Callee_eval/definedFunctionCallee}

===== Built-in methods

// Added
During type checking, built-in methods are resolved by:

// Added
${syntax: builtinMethodTypeIR}

// Added
${rulegroup-source: CallableType_ok/builtinMethodTypeIR}
${rulegroup-prose: CallableType_ok/builtinMethodTypeIR}

// Added
During runtime evaluation, built-in methods are resolved by:

// Added
${syntax: builtinMethodCallee}

// Added
${rulegroup-source: Callee_eval/builtinMethodCallee}
${rulegroup-prose: Callee_eval/builtinMethodCallee}

===== Extern methods

// Added
During type checking, extern methods are resolved by:

// Added
${syntax: externMethodTypeIR}

// Added
${rulegroup-source: CallableType_ok/externMethodTypeIR}
${rulegroup-prose: CallableType_ok/externMethodTypeIR}

// Added
During runtime evaluation, extern methods are resolved by:

// Added
${syntax: externMethodCallee}

// Added
${rulegroup-source: Callee_eval/externMethodCallee}
${rulegroup-prose: Callee_eval/externMethodCallee}

===== Parser apply methods

// Added
During type checking, parser apply methods are resolved by:

// Added
${syntax: parserApplyMethodTypeIR}

// Added
${rulegroup-source: CallableType_ok/parserApplyMethodTypeIR}
${rulegroup-prose: CallableType_ok/parserApplyMethodTypeIR}

// Added
During runtime evaluation, parser apply methods are resolved by:

// Added
${syntax: parserApplyMethodCallee}

// Added
${rulegroup-source: Callee_eval/parserApplyMethodCallee}
${rulegroup-prose: Callee_eval/parserApplyMethodCallee}

===== Control apply methods

// Added
During type checking, control apply methods are resolved by:

// Added
${syntax: controlApplyMethodTypeIR}

// Added
${rulegroup-source: CallableType_ok/controlApplyMethodTypeIR}
${rulegroup-prose: CallableType_ok/controlApplyMethodTypeIR}

// Added
During runtime evaluation, control apply methods are resolved by:

// Added
${syntax: controlApplyMethodCallee}

// Added
${rulegroup-source: Callee_eval/controlApplyMethodCallee}
${rulegroup-prose: Callee_eval/controlApplyMethodCallee}

===== Table apply methods

// Added
During type checking, table apply methods are resolved by:

// Added
${syntax: tableApplyMethodTypeIR}

// Added
${rulegroup-source: CallableType_ok/tableApplyMethodTypeIR}
${rulegroup-prose: CallableType_ok/tableApplyMethodTypeIR}

// Added
During runtime evaluation, table apply methods are resolved by:

// Added
${syntax: tableApplyMethodCallee}

// Added
${rulegroup-source: Callee_eval/tableApplyMethodCallee}
${rulegroup-prose: Callee_eval/tableApplyMethodCallee}
