ROUGE_STYLE=github
ROUGE_CSS=style

SPECTEC=p4spectec
SPECFILES=../spec-concrete/*/*.watsup
SPEC=P4-16-spec-new
RELEASE=P4-16-spec-release
DRAFT=P4-16-spec-draft

grammar.trimmed.adoc: grammar.adoc trim-asciidoc-tag-comments.py
	./trim-asciidoc-tag-comments.py $< > $@

spectec:
	cd .. && make release && cd docs

splice: spectec
	rm -r sections || true
	cp -r sections-skeleton sections
	SPLICEFILES=$$(find sections -type f -name '*.adoc' | xargs -I {} echo "-splice {}" | tr '\n' ' '); \
	../${SPECTEC} splice ${SPECFILES} -inplace $${SPLICEFILES} 2> error.log

${DRAFT}.html: ${SPEC}.adoc splice grammar.adoc grammar.trimmed.adoc
	time asciidoctor -q \
		-a rouge-css=$(ROUGE_CSS) \
		-o $@ $<

${RELEASE}.html: ${SPEC}.adoc splice grammar.adoc grammar.trimmed.adoc
	time asciidoctor -q \
		-a release \
		-a rouge-css=$(ROUGE_CSS) \
		-o $@ $<

${DRAFT}.pdf: ${SPEC}.adoc splice grammar.adoc grammar.trimmed.adoc
	time asciidoctor-pdf -q \
		-a pdf-fontsdir=resources/fonts \
		-a rouge-style=$(ROUGE_STYLE) \
		-o $@ $<

${RELEASE}.pdf: ${SPEC}.adoc splice grammar.adoc grammar.trimmed.adoc
	time asciidoctor-pdf -q \
		-a release \
		-a pdf-fontsdir=resources/fonts \
		-a rouge-style=$(ROUGE_STYLE) \
		-o $@ $<

draft: ${DRAFT}.html ${DRAFT}.pdf
draft-html: ${DRAFT}.html

release: ${RELEASE}.html ${RELEASE}.pdf
release-html: ${RELEASE}.html

clean:
	/bin/rm -f ${SPEC}.pdf ${SPEC}.html ${DRAFT}.html ${DRAFT}.pdf ${RELEASE}.html ${RELEASE}.pdf grammar.trimmed.adoc resources/figs/stem-*.png
